### ISSUE TITLE
Runtime Error before rename

### ISSUE THREAD

**Issue by Raighar** [Azelphur/PokemonGo-CalcyIV-Renamer#21]
Hi, 

I am getting the following error after the Pokemon was scanned and before anything regarding renaming happens:
```
Traceback (most recent call last):
  File "ivcheck.py", line 298, in <module>
    asyncio.run(Main(args).start())
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "ivcheck.py", line 90, in start
    actions = await self.get_actions(values)
  File "ivcheck.py", line 222, in get_actions
    clipboard_values = await self.get_data_from_clipboard()
  File "ivcheck.py", line 144, in get_data_from_clipboard
    raise Exception("Clipboard regex did not match")
Exception: Clipboard regex did not match
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0318C198>
Traceback (most recent call last):
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_subprocess.py", line 127, in __del__
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\proactor_events.py", line 86, in close
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 677, in call_soon
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 469, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03192540>
Traceback (most recent call last):
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\proactor_events.py", line 95, in __del__
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\proactor_events.py", line 86, in close
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 677, in call_soon
  File "C:\Users\Markus\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 469, in _check_closed
RuntimeError: Event loop is closed
```

What exactly is causing this? Thanks in advance.

**Comment by AliceGrey** [comment]
I'm pretty sure my error is related to this too. #18 
`2018-10-21 19:47:16,990 - ivcheck - DEBUG - logcat line received: D/MainService(
11295): Received values: Id: 373 (Beldum), Nr: 374, CP: 539, Max HP: 61, Dust co
st: 3500, Level: 24.0, FastMove err, SpecialMove err, Gender 0, Level-up false:
2018-10-21 19:47:16,990 - ivcheck - DEBUG - RE_CALCY_IV matched
2018-10-21 19:47:16,990 - PokemonGo - DEBUG - Running ['adb', '-s', 'ZY2244L65L'
, 'shell', 'am broadcast -a clipper.get']
2018-10-21 19:47:17,100 - PokemonGo - DEBUG - Return code 0
Traceback (most recent call last):
  File "ivcheck.py", line 298, in <module>
    asyncio.run(Main(args).start())
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ru
nners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_events.py", line 568, in run_until_complete
    return future.result()
  File "ivcheck.py", line 90, in start
    actions = await self.get_actions(values)
  File "ivcheck.py", line 222, in get_actions
    clipboard_values = await self.get_data_from_clipboard()
  File "ivcheck.py", line 144, in get_data_from_clipboard
    raise Exception("Clipboard regex did not match")
Exception: Clipboard regex did not match
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x022BFFA8>
Traceback (most recent call last):
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_subprocess.py", line 127, in __del__
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_subprocess.py", line 104, in close
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\pr
oactor_events.py", line 86, in close
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_events.py", line 672, in call_soon
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_events.py", line 461, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x022D4390
>
Traceback (most recent call last):
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\pr
oactor_events.py", line 95, in __del__
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\pr
oactor_events.py", line 86, in close
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_events.py", line 672, in call_soon
  File "C:\Users\Fenrir\AppData\Local\Programs\Python\Python37-32\lib\asyncio\ba
se_events.py", line 461, in _check_closed
RuntimeError: Event loop is closed`

**Comment by Azelphur** [comment]
Both of you have invalid regexes in your config.yaml - the regex in your config.yaml must match your calcy IV renaming pattern.

**Comment by AliceGrey** [comment]
@Azelphur That fixed it. Wasn't sure what that was for in the config.

**Comment by Raighar** [comment]
@Azelphur Yeah, that makes sense. So I need to have the IV%Min and IV%Max block in my renaming scheme to make the script work properly right? Is there no other way?

**Comment by esauvisky** [comment]
I found a way around that. I included lots of non-breaking spaces at the end of the renaming scheme and the IV-Range after them, while simultaneously changing the regexp to match it there.

As PoGo's limit is 12 characters, if you make your string long enough the IV range will never show up on your pokémon's name, however the script **will** be able to fetch and parse the whole sentence ;)

**Comment by Raighar** [comment]
@esauvisky Holy cow! This is smart as hell :) Thank you very much!

**Comment by Azelphur** [comment]
That's a really clever idea! we'll have to add that to the documentation.

Looks like everything here is resolved now, so I'll go ahead and close this one.
