### ISSUE TITLE
Issue during appraisal

### ISSUE THREAD

**Issue by Patralos** [Azelphur/PokemonGo-CalcyIV-Renamer#26]
Hi,

doing a appraisal always crashes with:

````
Traceback (most recent call last):
  File "ivcheck.py", line 318, in <module>
    asyncio.run(Main(args).start())
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "ivcheck.py", line 96, in start
    while await self.check_appraising():
  File "ivcheck.py", line 156, in check_appraising
    crop = screencap.crop(self.config['locations']['appraisal_box'])
  File "C:\Program Files\Python37\lib\site-packages\PIL\Image.py", line 1113, in crop
    return self._new(self._crop(self.im, box))
  File "C:\Program Files\Python37\lib\site-packages\PIL\Image.py", line 1127, in _crop
    x0, y0, x1, y1 = map(int, map(round, box))
TypeError: type str doesn't define __round__ method
````

Did someone get this error before?

Thx,
Patrick

**Comment by Patralos** [comment]
Hey,

I just found the issue, there was an space in one of the coordinates. Now I need to find out, why it is not pressing the save button on calcyiv.

Thx for your help :)
