### ISSUE TITLE
An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by freako89** [Azelphur/PokemonGo-CalcyIV-Renamer#4]
Hi,

I got this error from your updated PokemonGo-CalcyIV-Renamer code.

> 2018-07-07 17:39:37,572 - PokemonGo - DEBUG - Running ['adb', 'devices']
> 2018-07-07 17:39:37,618 - PokemonGo - DEBUG - Return code 0
> 2018-07-07 17:39:37,625 - PokemonGo - DEBUG - Running ['adb', '-s', u'7c719667', 'shell', 'am broadcast -a tesmath.calcy.ACTION_HIDE_BUTTON -n tesmath.calcy/.IntentReceiver']
> 2018-07-07 17:39:38,503 - PokemonGo - DEBUG - Return code 0
> 2018-07-07 17:39:38,503 - PokemonGo - DEBUG - Running ['adb', '-s', u'7c719667', 'shell', 'pidof', '-s', 'tesmath.calcy']
> 2018-07-07 17:39:38,650 - PokemonGo - DEBUG - Return code 0
> Traceback (most recent call last):
>   File ".\ivcheck_modified_xiaomi_mimax.py", line 63, in <module>
>     p.read_logcat()
>   File "C:\Users\a\Desktop\platform-tools_xiaomi\pokemonlib.py", line 165, in read_logcat
>     while select.select([self.logcat_task.stdout], [], [], 0.1)[0] != []:
> select.error: (10038, 'An operation was attempted on something that is not a socket')

May I know how do I resolve this issue?
Thanks!

**Comment by vansydy** [comment]
Getting similar on Windows, 

`    while select.select([self.logcat_task.stdout], [], [], 0.1)[0] != []:
OSError: [WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed
`

My understanding is 'select' is more limited on Windows than Unix based systems. Fix should be using a a new thread. @Azelphur

**Comment by EDIDDD** [comment]
Same problem on windows for me : 
2018-07-18 22:03:26,292 - PokemonGo - DEBUG - Running ['adb', 'devices']
2018-07-18 22:03:26,308 - PokemonGo - DEBUG - Return code 0
2018-07-18 22:03:26,308 - PokemonGo - DEBUG - Running ['adb', '-s', 'ac533083', 'shell', 'am broadcast -a tesmath.calcy.ACTION_HIDE_BUTTON -n tesmath.calcy/.IntentReceiver']
2018-07-18 22:03:26,495 - PokemonGo - DEBUG - Return code 0
2018-07-18 22:03:26,495 - PokemonGo - DEBUG - Running ['adb', '-s', 'ac533083', 'shell', 'pidof', '-s', 'tesmath.calcy']
2018-07-18 22:03:26,573 - PokemonGo - DEBUG - Return code 0
Traceback (most recent call last):
  File "C:\Python34\PokemonGo\ivcheck.py", line 63, in <module>
    p.read_logcat()
  File "C:\Python34\PokemonGo\pokemonlib.py", line 165, in read_logcat
    while select.select([self.logcat_task.stdout], [], [], 0.1)[0] != []:
OSError: [WinError 10093] Soit l\u2019application n\u2019a pas appelé WSAStartup, soit WSAStartup a échoué2018-07-18 22:03:26,292 - PokemonGo - DEBUG - Running ['adb', 'devices']
2018-07-18 22:03:26,308 - PokemonGo - DEBUG - Return code 0
2018-07-18 22:03:26,308 - PokemonGo - DEBUG - Running ['adb', '-s', 'ac533083', 'shell', 'am broadcast -a tesmath.calcy.ACTION_HIDE_BUTTON -n tesmath.calcy/.IntentReceiver']
2018-07-18 22:03:26,495 - PokemonGo - DEBUG - Return code 0
2018-07-18 22:03:26,495 - PokemonGo - DEBUG - Running ['adb', '-s', 'ac533083', 'shell', 'pidof', '-s', 'tesmath.calcy']
2018-07-18 22:03:26,573 - PokemonGo - DEBUG - Return code 0
Traceback (most recent call last):
  File "C:\Python34\PokemonGo\ivcheck.py", line 63, in <module>
    p.read_logcat()
  File "C:\Python34\PokemonGo\pokemonlib.py", line 165, in read_logcat
    while select.select([self.logcat_task.stdout], [], [], 0.1)[0] != []:
OSError: [WinError 10093] Soit l\u2019application n\u2019a pas appelé WSAStartup, soit WSAStartup a échoué

**Comment by Azelphur** [comment]
Can you guys give this another try now? Done a rewrite which should be faster/better, you may need to edit config.yaml to suit your phones.

**Comment by Azelphur** [comment]
Closing due to inactivity, reopen if you have a new issue.
